name: Multi jobs
on:
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: print job name
        run: echo "job name ${{ github.job }}"

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: print job 2 name
        run: echo "job ${{ github.job }}"
